# Generated by Django 4.2.4 on 2023-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_alter_task_due_date_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
